bump lib dependencies
rspective/voucherify-android-sdk pull request #23
Opened 2016-12-02 13:09 UTC by ktalanda

- retrofit 2.1.0,
- okHttp 3.5.0
- rxJava 1.2.3
- rxAndroid 1.2.1

2016-12-04 17:24 UTC, polok requested changes
The API has to be flexible. We can't force to use Observables.

2016-12-04 17:24 UTC, polok commented on library/src/main/java/pl/rspective/voucherify/android/client/api/VoucherifyApi.java
> +    Observable<VoucherResponse> validateVoucher(@QueryMap Map<String, String> queryParams);
Why we force users to use Observables ? What if someone doesn't want to use RxJava/Android world, what if someone what to use a normal asynchronous call? I would rather think about 'Call' - https://square.github.io/retrofit/2.x/retrofit/retrofit2/Call.html

The current version of the SDK allows the users to call API in the synchronous, asynchronous or rx way.

2016-12-05 08:30 UTC, ktalanda commented on library/src/main/java/pl/rspective/voucherify/android/client/api/VoucherifyApi.java
> +    Observable<VoucherResponse> validateVoucher(@QueryMap Map<String, String> queryParams);
right, will get back to synchronous retrofit calls, thx :+1:

2016-12-08 10:32 UTC, polok requested changes
Now, I like it :).
However, before we merge this. There are two small issues related to our README file. Please, update `proguard` section and `RetrofitError`in the examples as there is no such class in retrofit 2.

2016-12-08 17:43 UTC, ktalanda commented
👍

2016-12-08 20:26 UTC, polok approved these changes
👍

2016-12-08 20:27 UTC, merged